### ISSUE TITLE
Session ID is not used as URL parameter anymore.

### ISSUE THREAD

**Issue by Carlosvice** [lizardmedia/product-attachments-magento2#29]
Hello,

I´m trying your extension in my project but when I try to run the product edit form, it displays this message"Session ID is not used as URL parameter anymore.", the problem is apparently in Attachments.php in the line where it calls this method: 

'url' => $this->urlBuilder->addSessionParam()->getUrl(
                    'downloadable/attachment_file/upload',
                    [Attachment::ATTACHMENT_TYPE => 'attachments', '_secure' => true]
                )

under the method: $attachmentUploader['arguments']['data']['config']

So far I´ve just installed the extension via composer on a clean magento install

I´m quite new to magento, and I don´t understand what the problem is, Could you please help me?

Thanks in advance.

**Comment by bartoszkubicki** [comment]
@Carlosvice please let me know what magento version do you use. So far module has been tested and worked on magento 2.2+ and 2.3+

**Comment by Carlosvice** [comment]
@bartoszkubicki  Sure, it´s 2.3.5.

Thanks!

**Comment by bartoszkubicki** [comment]
https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Url.php
This change had to be added in 2.3.5 or 2.3.4. We have it tested on 2.3.3. I am merging fix for it. Please let me know if it works, and please report any issues with incompatibility with 2.3.5. Thank you!

**Comment by bartoszkubicki** [comment]
Please make sure to bump module's compsoer version to 1.3.3

**Comment by Carlosvice** [comment]
@bartoszkubicki Sure thing Bartosz, I'll replace the file and let you know if I encounter any other issue. I´m running composer 1.10.1 updated on 2020-03-13 Is it ok, or should I downgrade?

Thanks!

**Comment by bartoszkubicki** [comment]
I don't think composer does really matter here

**Comment by Carlosvice** [comment]
> 
> 
> Please make sure to bump module's compsoer version to 1.3.3

What was you refering to?

I replaced the file named "Url.php" contained in "vendor/magento/framework/" with the one on your reply but with no luck. Should I try aything else?

**Comment by bartoszkubicki** [comment]
@Carlosvice Do not replace any magento files. Download the newest version of our module and replace old one if you have installed it in `app/code`/ If you have installed it by recommended composer way (https://github.com/lizardmedia/product-attachments-magento2/blob/master/README.md), just run `composer update lizardmedia/module-product-attachments`

**Comment by Carlosvice** [comment]
@bartoszkubicki  Ok, I restored the file I changed, although I think it was the same, and ran the composer update. I've just understood you, sorry, now I'm running version 1.3.3 of your extension.

It does no longer triggers the same error but the form doesn't show anything under the attachments section.

Thanks a lot Bartosz.
![Issue](https://user-images.githubusercontent.com/47548273/81412072-e9699c80-9108-11ea-9cde-acf58930ee94.png)

**Comment by bartoszkubicki** [comment]
@Carlosvice I will check that, it should work.

**Comment by bartoszkubicki** [comment]
@Carlosvice check newest release 1.3.4. - I have just fixed product page problem.

**Comment by Carlosvice** [comment]
@bartoszkubicki Done the upgrade but the form stays the same. Can I help you in any way?

Thanks!

**Comment by Carlosvice** [comment]
@bartoszkubicki Wait I just checked the extension version and it's still 1.3.3. I'll try to update again.

**Comment by Carlosvice** [comment]
@bartoszkubicki Still no luck. Any other way I can help you, or is there something you would want me to share?
Thanks!

![Issue2](https://user-images.githubusercontent.com/47548273/81448738-83026f80-9144-11ea-86e1-efbc82d6cfef.png)

**Comment by bartoszkubicki** [comment]
I just have tested it on almost clean magento instal 2.3.4 and there is a form to upload url or a file. Can you share dev console of browser?

**Comment by Carlosvice** [comment]
Sure.
![Issue3](https://user-images.githubusercontent.com/47548273/81452431-7da92300-914c-11ea-93ef-24a856e3e552.png)
![Issue4](https://user-images.githubusercontent.com/47548273/81452432-7eda5000-914c-11ea-87d2-6701507f60a3.png)

**Comment by bartoszkubicki** [comment]
@Carlosvice looks like you have problem with loading static files, something with content security policy. It doesn't seem to be caused by module, rather its something with your installation. I will upgrade my installation to 2.3.5 and check if module still works. If so, I will have to close this issue.

**Comment by Carlosvice** [comment]
@bartoszkubicki Ok, please let me know whether you encounter the same issue or not. 

Thanks a lot!

**Comment by bartoszkubicki** [comment]
@Carlosvice tested today on magento 2.3.5. I am closing this issue, as I can't reproduce it further problems. Issue topic is fixed.

**Comment by Carlosvice** [comment]
@bartoszkubicki  Good! Thanks Bartosz, I´ll try on a clean install of Magento.

**Comment by Carlosvice** [comment]
@bartoszkubicki Hello! I managed to solve the csp errors and did a clean install (including OS, XAMPP, Magento and the extension), unfortunately the extension is still not working, could you help me again, I don´t know what could be, I don´t have errors in the log´s nor the console. Thank you!

Here´s a before and after installing the extension:
![P1](https://user-images.githubusercontent.com/47548273/82517890-c0231600-9ae3-11ea-918e-bc2c3924315a.png)

![P2](https://user-images.githubusercontent.com/47548273/82517892-c0bbac80-9ae3-11ea-9fd4-4cefa55fc1ee.png)

**Comment by Carlosvice** [comment]
@bartoszkubicki I´ve been wandering around the code and I noticed that it doesn´t appear anything under the fieldset of the section. Do you think I could be missing parts of your code?

![P3](https://user-images.githubusercontent.com/47548273/82564182-f42b2500-9b3d-11ea-8782-b1441a2da4da.png)

**Comment by bartoszkubicki** [comment]
@Carlosvice Ok I see that you've open another issue #34 . Closing this one.
